### ISSUE TITLE
Improper format in CSV files

### ISSUE THREAD

**Issue by PeterKraus** [peverati/ASCDB#1]
Dear Roberto, the CSV files are very useful, but I believe there is a problem on two lines:

The product `2733_05MeOHMeOH100_monA_S66x8` is listed twice, but it should be listed only once with stoichiometry `-2`:
https://github.com/peverati/ASCDB/blob/8f77eecd011f40e07b1fc0d2ac6b4e01c369f766/Evaluation/ASCDB_Eh.csv#L7

Here the stoichiometry of the last product is missing. I believe it should be `-1`:
https://github.com/peverati/ASCDB/blob/8f77eecd011f40e07b1fc0d2ac6b4e01c369f766/Evaluation/ASCDB_Eh.csv#L106

**Comment by peverati** [comment]
Thank you for spotting the typo Peter.
It has been fixed.
